#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1539300483                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : /presskit.zip          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Plantir is a plant tracking and reminder app to help you take care of your plants :)

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

app_short_name                            : "Plantir"


# Information About Yourself
your_name                                 : Cameron Holiman                                
your_link                                 : https://islandsprite.com                  
your_city                                 : Utah                                
email_address                             : contact@islandsprite.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : cameronholiman
github_username                           : mermaid
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Free!
    description                           : All the core functionality is free! Track as many plants & tasks as you want at no cost.
    fontawesome_icon_name                 : dollar-sign

  - title                                 : Privacy First
    description                           : Plantir does not track you. It does not require a login, and has no ads.
    fontawesome_icon_name                 : lock
    
  - title                                 : Infinite Schedule
    description                           : The infinite scrolling schedule tab will show you all the plants you have scheduled forever into the future!
    fontawesome_icon_name                 : calendar-alt

  - title                                 : Customizable Schedules
    description                           : Schedule tasks by day of the week or month, on a daily/weekly/monthly, even while on a specific day of the week (Every month on Sunday...)
    fontawesome_icon_name                 : clock

  - title                                 : Tons of Features
    description                           : Widgets, notifications, badges, themes, light & dark mode, 40+ custom icons, oh my!
    fontawesome_icon_name                 : grin-stars

  - title                                 : Pink
    description                           : Very very pink! But has custom themes in case you don't like pink ;) You can even choose your own color!
    fontawesome_icon_name                 : palette

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

# cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#FB6376"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FB6376"
feature_icons_background_color            : "#e6e6e6"

feature_icons_foreground_color_alternate  : "#263E0F"
feature_icons_background_color_alternate  : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"




destination: docs/

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown